ctnr := "tw3discordbot"

# installs the `.container` file on the current host
container-release: dockerfile-build podman-save deploy-locally systemd-reload systemd-restart-service

systemd-reload:
  sudo systemctl daemon-reload

systemd-restart-service:
  sudo systemctl restart {{ctnr}}.service

deploy-locally:
  sudo mkdir -p /etc/containers/systemd/{{ctnr}}
  sudo cp {{ctnr}}.container {{ctnr}}-image.tar /etc/containers/systemd/{{ctnr}}/

dockerfile-build:
    podman build .. --platform linux/arm64 --no-cache --rm --tag {{ctnr}} -f ./{{ctnr}}.Dockerfile

# saves the docker image into a `.tar` file
podman-save:
    rm -f ./{{ctnr}}-image.tar
    podman save --output ./{{ctnr}}-image.tar localhost/{{ctnr}}

release-make-zip:
  zip -r {{ctnr}}.release.zip {{ctnr}}.container {{ctnr}}-image.tar
